resources:
  - name: project_2_repo
    type: GitRepo
    configuration:
      path: deepikasl/basic-templates-example
      gitProvider: deepikaGithub
      branches:
        include: main    
pipelines:
  - name: sample_pipeline_project_2
    configuration:
      environmentVariables:
        readOnly:
          version: 1.0.0
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: project_2_repo
        execution:
          onExecute:
            - pushd ${res_"{{ .Values.PipelineConfig.resourceName }}"_repo_resourcePath}
            - ./run.sh project-2 $version
