resources:
  - name: {{ .Values.PipelineConfig.resourceName }}
    type: GitRepo
    configuration:
      path: deepikasl/basic-templates-example
      gitProvider: deepikaGithub
      branches:
        include: main    

pipelines:
  - name: {{ .Values.PipelineConfig.pipelineName }}
    configuration:
      environmentVariables:
        readOnly:
          version: {{ .Values.PipelineConfig.version }}
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
        execution:
          onExecute:
            - pushd ${res_"{{ .Values.PipelineConfig.resourceName }}"_resourcePath}
            - ./run.sh {{ .Values.PipelineConfig.serviceName }} $version
