resources:
  - name: git_repo
    type: GitRepo
    configuration:
      path: deepikasl/basic-templates-example
      gitProvider: deepikaGithub
      branches:
        include: main        

pipelines:
  - name: sample_pipeline_project_1
    configuration:
      environmentVariables:
        readOnly:
          version: 1.0.0
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
        execution:
          onExecute:
            - pushd $res_git_repo_resourcePath
            - ./run.sh project-1 $version
